# Builds TinyCC out of the third_party/tinycc submodule, as the compiler's
# in-process C backend (JIT mode). Included from CMakeLists.txt only when that
# submodule is checked out; without it the compiler builds exactly as before and
# JIT mode reports that it was not compiled in.
#
# TinyCC has its own configure/make, which cannot be reached from here on all
# three platforms, so what it would have produced is produced here instead:
# a config.h, the library itself (one translation unit, ONE_SOURCE), the tcc
# driver, and -- built by that driver, since parts of it are TinyCC assembly --
# the libtcc1 support archive every program it compiles links against. The
# archive, the runtime headers and (on Windows) the import definitions are
# staged into one directory, which is what tcc_set_lib_path() is given.

set(TCC_SRC "${CMAKE_CURRENT_SOURCE_DIR}/third_party/tinycc")
set(TCC_BUILD "${CMAKE_BINARY_DIR}/tcc")
set(TCC_STAGE "${CMAKE_BINARY_DIR}/tcclib")

if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|amd64)$" AND CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(tcc_arch x86_64)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64|ARM64)$")
    set(tcc_arch arm64)
else()
    message(STATUS "libtcc: no TinyCC backend for CPU '${CMAKE_SYSTEM_PROCESSOR}'; "
                   "building without JIT mode")
    return()
endif()

if(tcc_arch STREQUAL "x86_64")
    set(tcc_defines TCC_TARGET_X86_64)
else()
    set(tcc_defines TCC_TARGET_ARM64)
endif()
if(WIN32)
    list(APPEND tcc_defines TCC_TARGET_PE)
elseif(APPLE)
    list(APPEND tcc_defines TCC_TARGET_MACHO)
endif()

# --- config.h ----------------------------------------------------------------
# CONFIG_TCC_PREDEFS 0 makes TinyCC read include/tccdefs.h from the staged
# directory instead of from a string baked in by its own build tools, which are
# not run here. Bounds checking and backtraces are off: both pull in support
# objects that need the full Windows SDK headers, which TinyCC does not ship.

file(READ "${TCC_SRC}/VERSION" tcc_version)
string(STRIP "${tcc_version}" tcc_version)
set(tcc_config "/* Generated by cmake/libtcc.cmake. */
#define TCC_VERSION \"${tcc_version}\"
#define CONFIG_TCC_PREDEFS 0
#define CONFIG_TCC_BACKTRACE 0
#define CONFIG_TCC_BCHECK 0
")
# Debian-family systems put the C library's headers and objects under a
# machine triplet rather than directly in /usr/include and /usr/lib.
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    # Cross compilers such as Zig do not implement -print-multiarch, so retain
    # the libc ABI they were configured to target for TinyCC's system paths.
    if(CMAKE_C_COMPILER_TARGET MATCHES "linux-musl$")
        set(tcc_triplet "${tcc_arch}-linux-musl")
    else()
        execute_process(COMMAND ${CMAKE_C_COMPILER} -print-multiarch
                        OUTPUT_VARIABLE tcc_triplet OUTPUT_STRIP_TRAILING_WHITESPACE
                        ERROR_QUIET)
    endif()
    if(NOT tcc_triplet)
        set(tcc_triplet "${tcc_arch}-linux-gnu")
    endif()
    string(APPEND tcc_config "#define CONFIG_TRIPLET \"${tcc_triplet}\"\n")
endif()
# Written only when it changes, so reconfiguring does not rebuild TinyCC.
file(CONFIGURE OUTPUT "${TCC_BUILD}/config.h" CONTENT "${tcc_config}" @ONLY)

# --- the library and the driver ----------------------------------------------

add_library(libtcc STATIC "${TCC_SRC}/libtcc.c")
target_include_directories(libtcc PRIVATE "${TCC_BUILD}")
target_include_directories(libtcc SYSTEM PRIVATE "${TCC_SRC}")
# Expose only the API header: TinyCC's VERSION file shadows the C++ <version>
# header on case-insensitive filesystems (including the macOS CI runner).
# Keep this separate from the staged runtime headers, which also shadow the
# host compiler's standard headers.
configure_file("${TCC_SRC}/libtcc.h" "${TCC_BUILD}/api/libtcc.h" COPYONLY)
target_include_directories(libtcc SYSTEM PUBLIC "${TCC_BUILD}/api")
target_compile_definitions(libtcc PRIVATE ${tcc_defines} ONE_SOURCE=1)
# Without the rename the archive would be liblibtcc; PIC because the compiled
# program is relocated into memory the compiler owns.
set_target_properties(libtcc PROPERTIES
    C_STANDARD 99 OUTPUT_NAME tcc POSITION_INDEPENDENT_CODE ON)

# The driver exists to build libtcc1.a below: parts of it are TinyCC assembly,
# which only TinyCC assembles.
add_executable(tcc_driver "${TCC_SRC}/tcc.c")
target_include_directories(tcc_driver PRIVATE "${TCC_BUILD}")
target_compile_definitions(tcc_driver PRIVATE ${tcc_defines} ONE_SOURCE=0)
target_link_libraries(tcc_driver PRIVATE libtcc)
set_target_properties(tcc_driver PROPERTIES
    C_STANDARD 99 OUTPUT_NAME tcc RUNTIME_OUTPUT_DIRECTORY "${TCC_BUILD}")
# The Visual Studio and Xcode generators add a per-configuration subdirectory
# to every output path unless it is overridden for each configuration by name.
foreach(cfg IN LISTS CMAKE_CONFIGURATION_TYPES)
    string(TOUPPER "${cfg}" cfgu)
    set_target_properties(tcc_driver PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY_${cfgu} "${TCC_BUILD}")
endforeach()

# Third-party code: its warnings are not this project's to act on. /W0 rather
# than /w so the Visual Studio generator recognises it as the warning level and
# does not also emit its own.
foreach(t IN ITEMS libtcc tcc_driver)
    target_compile_options(${t} PRIVATE $<IF:$<BOOL:${MSVC}>,/W0,-w>)
endforeach()
if(NOT WIN32)
    target_link_libraries(libtcc PUBLIC ${CMAKE_DL_LIBS} m)
endif()

# --- staged runtime directory ------------------------------------------------
# What tcc_set_lib_path() is pointed at, laid out the way TinyCC's own install
# is: its headers under include/, and the support archive where the target's
# default library path looks for it (lib/ on Windows, the root elsewhere).

file(COPY "${TCC_SRC}/include/" DESTINATION "${TCC_STAGE}/include")
if(WIN32)
    set(tcc_libdir "${TCC_STAGE}/lib")
    # TinyCC's Windows headers, and the .def files naming what the system DLLs
    # export. It ships no <windows.h>; the runtime declares the few Win32
    # functions it needs itself when compiled by TinyCC.
    file(COPY "${TCC_SRC}/win32/include/" DESTINATION "${TCC_STAGE}/include")
    file(GLOB tcc_defs "${TCC_SRC}/win32/lib/*.def")
    file(COPY ${tcc_defs} DESTINATION "${tcc_libdir}")
else()
    set(tcc_libdir "${TCC_STAGE}")
endif()

# --- libtcc1 -----------------------------------------------------------------
# The compiler support routines every TinyCC-compiled program links against.
# This is TinyCC's lib/Makefile object list for the target, minus the pieces
# only a standalone executable or DLL needs (the C runtime startup code, bounds
# checking, backtraces), none of which an in-memory run reaches.

if(tcc_arch STREQUAL "arm64")
    set(tcc1_srcs lib/lib-arm64.c)
    if(NOT WIN32 AND NOT APPLE)
        list(APPEND tcc1_srcs lib/armflush.c)
    endif()
else()
    set(tcc1_srcs lib/libtcc1.c)
    if(NOT WIN32)
        list(APPEND tcc1_srcs lib/va_list.c)
    endif()
endif()
list(APPEND tcc1_srcs lib/stdatomic.c lib/atomic.S lib/builtin.c
                      lib/alloca.S lib/alloca-bt.S)
if(WIN32)
    # crt1.c is where the Windows _runmain lives — the entry point tcc_run()
    # calls, which the platform-independent lib/runmain.c defines only for the
    # ELF and Mach-O targets.
    list(APPEND tcc1_srcs win32/lib/chkstk.S win32/lib/winex.c win32/lib/crt1.c)
elseif(NOT APPLE)
    list(APPEND tcc1_srcs lib/dsohandle.c)
endif()

# -B is the staged directory the compiled program will also be built against;
# -I reaches config.h, which some of these sources include.
set(tcc1_flags -B${TCC_STAGE} -I${TCC_BUILD} -I${TCC_SRC})
set(tcc1_objs "")
file(MAKE_DIRECTORY "${TCC_BUILD}/obj")   # tcc writes objects, it does not create paths.
foreach(src IN LISTS tcc1_srcs)
    get_filename_component(obj "${src}" NAME_WE)
    set(obj "${TCC_BUILD}/obj/${obj}.o")
    add_custom_command(OUTPUT "${obj}"
        COMMAND "${TCC_BUILD}/tcc${CMAKE_EXECUTABLE_SUFFIX}" ${tcc1_flags}
                -c "${TCC_SRC}/${src}" -o "${obj}"
        DEPENDS tcc_driver "${TCC_SRC}/${src}"
        COMMENT "tcc ${src}"
        VERBATIM)
    list(APPEND tcc1_objs "${obj}")
endforeach()

add_custom_command(OUTPUT "${tcc_libdir}/libtcc1.a"
    COMMAND "${TCC_BUILD}/tcc${CMAKE_EXECUTABLE_SUFFIX}" -ar rcs
            "${tcc_libdir}/libtcc1.a" ${tcc1_objs}
    DEPENDS ${tcc1_objs}
    COMMENT "tcc -ar libtcc1.a"
    VERBATIM)

# tcc_run() loads this one separately: it is what calls the program's main and
# runs its constructors, so it is deliberately not inside the archive.
add_custom_command(OUTPUT "${tcc_libdir}/runmain.o"
    COMMAND "${TCC_BUILD}/tcc${CMAKE_EXECUTABLE_SUFFIX}" ${tcc1_flags}
            -c "${TCC_SRC}/lib/runmain.c" -o "${tcc_libdir}/runmain.o"
    DEPENDS tcc_driver "${TCC_SRC}/lib/runmain.c"
    COMMENT "tcc lib/runmain.c"
    VERBATIM)

add_custom_target(tcc_runtime ALL
    DEPENDS "${tcc_libdir}/libtcc1.a" "${tcc_libdir}/runmain.o")

set(GOOSE_HAVE_LIBTCC ON)
message(STATUS "libtcc: TinyCC ${tcc_version} backend for ${tcc_arch}")
